MUFREDAT = {
    # ==========================================
    # FAZ 1: KÖKLER (1 - 14. Adımlar)
    # ==========================================
    1: {"faz": "Faz 1: Kökler", "ust_seviye": "1. Uyku Otonomisi", "alt_seviye": "Alarm Disiplini", "varsayilan_gorev": "Akşam alarmı kur ve sabah kendin uyan.", "varsayilan_tefekkur": "Güne kendi iradenle başlamak ne hissettirdi?"},
    2: {"faz": "Faz 1: Kökler", "ust_seviye": "1. Uyku Otonomisi", "alt_seviye": "Yatak Düzeni", "varsayilan_gorev": "Yorganını katla ve yatağını havalandır.", "varsayilan_tefekkur": "Düzenli bir odaya girmek sana nasıl bir huzur verdi?"},
    3: {"faz": "Faz 1: Kökler", "ust_seviye": "2. Beden Hijyeni", "alt_seviye": "Diş Sağlığı", "varsayilan_gorev": "Dişlerini fırçala, lavaboyu temiz bırak.", "varsayilan_tefekkur": "Bedenine bakmak, ona duyduğun saygıyı artırır mı?"},
    4: {"faz": "Faz 1: Kökler", "ust_seviye": "2. Beden Hijyeni", "alt_seviye": "El ve Yüz Yıkama", "varsayilan_gorev": "Dışarıdan eve girer girmez ellerini ve yüzünü sabunla yıka.", "varsayilan_tefekkur": "Suyla arınmak ruhunu da hafifletti mi?"},
    5: {"faz": "Faz 1: Kökler", "ust_seviye": "3. Giyim ve Mahremiyet", "alt_seviye": "Kıyafet Seçimi", "varsayilan_gorev": "Hava durumuna uygun kıyafetlerini kendin seç ve giyin.", "varsayilan_tefekkur": "Kendi bedeninin sorumluluğunu almak nasıl bir duygu?"},
    6: {"faz": "Faz 1: Kökler", "ust_seviye": "3. Giyim ve Mahremiyet", "alt_seviye": "Kıyafet Katlama", "varsayilan_gorev": "Çıkardığın kıyafetleri sağa sola atmadan katla veya kirliye at.", "varsayilan_tefekkur": "Eşyalarına özen göstermek, onlara teşekkür etmenin bir yolu mudur?"},
    7: {"faz": "Faz 1: Kökler", "ust_seviye": "4. Mekan Düzeni", "alt_seviye": "Çalışma Masası", "varsayilan_gorev": "Masandaki kitap ve kalemleri işin bitince düzenle.", "varsayilan_tefekkur": "Dışarıdaki düzen, zihnindeki karmaşayı azaltıyor mu?"},
    8: {"faz": "Faz 1: Kökler", "ust_seviye": "4. Mekan Düzeni", "alt_seviye": "Oyun Alanı", "varsayilan_gorev": "Oyunun bitince oyuncaklarını veya eşyalarını kutusuna kaldır.", "varsayilan_tefekkur": "Bir işi 'tamamlamak' sence neden önemlidir?"},
    9: {"faz": "Faz 1: Kökler", "ust_seviye": "5. Beslenme Özbakımı", "alt_seviye": "Su Tüketimi", "varsayilan_gorev": "Bugün kendi su takibini yap ve gün boyu yeterli su iç.", "varsayilan_tefekkur": "Vücudunun da bir fidan gibi suya ihtiyacı olduğunu fark ettin mi?"},
    10: {"faz": "Faz 1: Kökler", "ust_seviye": "5. Beslenme Özbakımı", "alt_seviye": "Kendi Yemeğini Yeme", "varsayilan_gorev": "Yemeğini dökmeden, kendi başına ve israf etmeden ye.", "varsayilan_tefekkur": "Yediğin yemeğin enerjisiyle bugün ne ürettin?"},
    11: {"faz": "Faz 1: Kökler", "ust_seviye": "6. Eşya Hukuku", "alt_seviye": "Çanta Hazırlığı", "varsayilan_gorev": "Ertesi günün okul çantasını akşamdan hazırla ve kapıya koy.", "varsayilan_tefekkur": "Geleceği planlamak seni sabah telaşından kurtardı mı?"},
    12: {"faz": "Faz 1: Kökler", "ust_seviye": "6. Eşya Hukuku", "alt_seviye": "Ayakkabı Temizliği", "varsayilan_gorev": "Dışarıdan gelince ayakkabılarını düzgünce yerine koy.", "varsayilan_tefekkur": "Eşyanın hakkını vermek diye bir şey duydun mu?"},
    13: {"faz": "Faz 1: Kökler", "ust_seviye": "6. Eşya Hukuku", "alt_seviye": "Çöp Atma", "varsayilan_gorev": "Odandaki veya masandaki çöpü ana çöp kutusuna boşalt.", "varsayilan_tefekkur": "Kendi atığının sorumluluğunu almak sana ne öğretti?"},
    14: {"faz": "Faz 1: Kökler", "ust_seviye": "6. Eşya Hukuku", "alt_seviye": "Kapı Çıkış Rutini", "varsayilan_gorev": "Evden çıkarken son kez ışıkları kontrol et.", "varsayilan_tefekkur": "Aileni ve evini koruma bilinci sende ne uyandırıyor?"},

    # ==========================================
    # FAZ 2: BAĞLAR (15 - 28. Adımlar)
    # ==========================================
    15: {"faz": "Faz 2: Bağlar", "ust_seviye": "7. Mutfak Kültürü", "alt_seviye": "Masa Kurulumu", "varsayilan_gorev": "Aile yemeklerinde masayı kurmaya yardım et.", "varsayilan_tefekkur": "Kendi ellerinle kurduğun sofrada aileni görmek kalbinde ne uyandırdı?"},
    16: {"faz": "Faz 2: Bağlar", "ust_seviye": "7. Mutfak Kültürü", "alt_seviye": "Tabak Toplama", "varsayilan_gorev": "Yemekten sonra kendi tabağını ve bardağını mutfağa taşı.", "varsayilan_tefekkur": "Ailene hizmet etmek bağımsızlığını kısıtlar mı, yoksa güçlendirir mi?"},
    17: {"faz": "Faz 2: Bağlar", "ust_seviye": "8. Kardeş ve Aile Hukuku", "alt_seviye": "Eşya Paylaşımı", "varsayilan_gorev": "Sevdiğin bir eşyanı kardeşine veya bir arkadaşına ödünç ver.", "varsayilan_tefekkur": "Paylaşmak, sahip olduğun şeye değer katar mı?"},
    18: {"faz": "Faz 2: Bağlar", "ust_seviye": "8. Kardeş ve Aile Hukuku", "alt_seviye": "Teşekkür Etme", "varsayilan_gorev": "Evdeki birine bugün senin için yaptığı küçük bir şey için teşekkür et.", "varsayilan_tefekkur": "İyiliği fark etmek ve dile getirmek aranızdaki bağı nasıl etkiledi?"},
    19: {"faz": "Faz 2: Bağlar", "ust_seviye": "9. Aile İçi Sorumluluk", "alt_seviye": "Ortak Alan Düzeni", "varsayilan_gorev": "Salondaki veya ortak kullanım alanındaki bir dağınıklığı düzelt.", "varsayilan_tefekkur": "Sadece kendi odandan değil, bütünden sorumlu olmak ne hissettiriyor?"},
    20: {"faz": "Faz 2: Bağlar", "ust_seviye": "9. Aile İçi Sorumluluk", "alt_seviye": "Bitki ve Canlı Bakımı", "varsayilan_gorev": "Evdeki bir bitkiyi sula veya evcil hayvanın bakımıyla ilgilen.", "varsayilan_tefekkur": "Sana muhtaç bir canlıya hayat vermek merhametini nasıl besler?"},
    21: {"faz": "Faz 2: Bağlar", "ust_seviye": "10. Büyüklere Saygı", "alt_seviye": "Karşılama Zarafeti", "varsayilan_gorev": "Dışarıdan gelen bir büyüğünü kapıda güler yüzle karşıla.", "varsayilan_tefekkur": "İnsanları nasıl karşıladığın, onlara verdiğin değerin bir ölçüsü müdür?"},
    22: {"faz": "Faz 2: Bağlar", "ust_seviye": "10. Büyüklere Saygı", "alt_seviye": "Söz Kesmeme", "varsayilan_gorev": "Konuşan birinin sözünü kesmeden, onu sonuna kadar dinle.", "varsayilan_tefekkur": "Dinlemek, konuşmaktan daha zor ama daha değerli olabilir mi?"},
    23: {"faz": "Faz 2: Bağlar", "ust_seviye": "11. İletişim Zarafeti", "alt_seviye": "Hal Hatır Sorma", "varsayilan_gorev": "Güne başlarken ailendeki bireylere 'Nasılsın?' diye sor.", "varsayilan_tefekkur": "Birinin nasıl olduğunu gerçekten merak etmek aranızdaki buzları eritir mi?"},
    24: {"faz": "Faz 2: Bağlar", "ust_seviye": "11. İletişim Zarafeti", "alt_seviye": "Ses Tonu Kontrolü", "varsayilan_gorev": "Evin içinde bağırarak konuşmak yerine sakin bir ses tonu kullan.", "varsayilan_tefekkur": "Bağırmadan konuşmak sözlerinin gücünü artırır mı?"},
    25: {"faz": "Faz 2: Bağlar", "ust_seviye": "11. İletişim Zarafeti", "alt_seviye": "Kapı Çalma Adabı", "varsayilan_gorev": "Başkasının odasına girerken mutlaka kapıyı vur ve izin bekle.", "varsayilan_tefekkur": "Başkalarının özel alanına saygı duymak güven inşa eder mi?"},
    26: {"faz": "Faz 2: Bağlar", "ust_seviye": "12. Misafirperverlik", "alt_seviye": "İkram Kültürü", "varsayilan_gorev": "Gelen misafire kolonya veya ufak bir ikram tut.", "varsayilan_tefekkur": "İkram etmek, sadece yiyecek vermek midir, yoksa gönül almak mı?"},
    27: {"faz": "Faz 2: Bağlar", "ust_seviye": "12. Misafirperverlik", "alt_seviye": "Uğurlama Adabı", "varsayilan_gorev": "Evden ayrılan bir misafiri kapıya kadar yolcu et.", "varsayilan_tefekkur": "Güler yüzle uğurlanan bir insan geri dönmek ister mi?"},
    28: {"faz": "Faz 2: Bağlar", "ust_seviye": "12. Misafirperverlik", "alt_seviye": "Yemek Şükrü", "varsayilan_gorev": "Yemekten kalkarken yemeği hazırlayana 'Eline sağlık' de.", "varsayilan_tefekkur": "Teşekkür etmek yemeğin lezzetini artırır mı?"},

    # ==========================================
    # FAZ 3: PUSULA (29 - 42. Adımlar)
    # ==========================================
    29: {"faz": "Faz 3: Pusula", "ust_seviye": "13. Ekran Otonomisi", "alt_seviye": "Süreli Kullanım", "varsayilan_gorev": "Oyun/tablet süren dolduğunda cihazı itiraz etmeden kapat.", "varsayilan_tefekkur": "Bir makineye 'hayır' diyebilmek iradeni nasıl güçlendirdi?"},
    30: {"faz": "Faz 3: Pusula", "ust_seviye": "13. Ekran Otonomisi", "alt_seviye": "İçerik Seçiciliği", "varsayilan_gorev": "Boş bir video yerine sana yeni bir şey öğretecek bir içerik seç.", "varsayilan_tefekkur": "Zihnini ne ile beslediğin, nasıl düşündüğünü etkiler mi?"},
    31: {"faz": "Faz 3: Pusula", "ust_seviye": "14. Zaman Yönetimi", "alt_seviye": "Öncelik Belirleme", "varsayilan_gorev": "Önce sorumluluğunu (ödev/görev) bitir, sonra eğlenceye geç.", "varsayilan_tefekkur": "Zoru önce yapmak, kalanın tadını çıkarmayı sağlar mı?"},
    32: {"faz": "Faz 3: Pusula", "ust_seviye": "14. Zaman Yönetimi", "alt_seviye": "5 Dakika Kuralı", "varsayilan_gorev": "Başlamakta zorlandığın bir işe sadece 5 dakika odaklanarak başla.", "varsayilan_tefekkur": "Başlamak işin yarısıdır sözü sence doğru mu?"},
    33: {"faz": "Faz 3: Pusula", "ust_seviye": "15. Bilişsel Odak", "alt_seviye": "Tek İş Kuralı", "varsayilan_gorev": "Yemek yerken veya biriyle konuşurken ekrana/telefona bakma.", "varsayilan_tefekkur": "Sadece bir şeye odaklanmak anı yaşamayı kolaylaştırdı mı?"},
    34: {"faz": "Faz 3: Pusula", "ust_seviye": "15. Bilişsel Odak", "alt_seviye": "Dikkat Toplama", "varsayilan_gorev": "Okuduğun kitabı veya yaptığın işi bölünmeden 15 dakika sürdür.", "varsayilan_tefekkur": "Zihnini bir noktada tutabilmek sana nasıl bir güç veriyor?"},
    35: {"faz": "Faz 3: Pusula", "ust_seviye": "16. Bilgi Tüketimi", "alt_seviye": "Doğru Kaynak", "varsayilan_gorev": "İnternette gördüğün ilginç bir bilginin doğruluğunu bir büyüğüne sor.", "varsayilan_tefekkur": "Her gördüğümüze inanmamak bizi nasıl korur?"},
    36: {"faz": "Faz 3: Pusula", "ust_seviye": "16. Bilgi Tüketimi", "alt_seviye": "Fayda Analizi", "varsayilan_gorev": "Tükettiğin oyunun veya videonun sana ne kattığını kısaca düşün.", "varsayilan_tefekkur": "Eğlenmek güzeldir, peki gelişerek eğlenmek mümkün mü?"},
    37: {"faz": "Faz 3: Pusula", "ust_seviye": "17. Zihinsel Hijyen", "alt_seviye": "Can Sıkıntısı İradesi", "varsayilan_gorev": "Canın sıkıldığında hemen ekrana koşma, 10 dakika sıkılmaya izin ver.", "varsayilan_tefekkur": "Can sıkıntısı yaratıcılığın ve yeni oyunların kapısı olabilir mi?"},
    38: {"faz": "Faz 3: Pusula", "ust_seviye": "17. Zihinsel Hijyen", "alt_seviye": "Çevrimdışı Sohbet", "varsayilan_gorev": "Ekranları kapatıp ailenle sadece konuşarak zaman geçir.", "varsayilan_tefekkur": "Gerçek insan sesi, dijital seslerden daha mı sıcak?"},
    39: {"faz": "Faz 3: Pusula", "ust_seviye": "17. Zihinsel Hijyen", "alt_seviye": "Doğa Gözlemi", "varsayilan_gorev": "Pencereden veya balkondan 5 dakika boyunca sadece dışarıyı izle.", "varsayilan_tefekkur": "Gözünü ekranın ışığından ufuk çizgisine çevirmek zihnini açtı mı?"},
    40: {"faz": "Faz 3: Pusula", "ust_seviye": "18. Dijital Mahremiyet", "alt_seviye": "Kişisel Veri Koruma", "varsayilan_gorev": "İnternette oyun oynarken adını, yaşını ve adresini gizli tut.", "varsayilan_tefekkur": "Görünmez sınırlar çekmek dijital dünyada seni nasıl korur?"},
    41: {"faz": "Faz 3: Pusula", "ust_seviye": "18. Dijital Mahremiyet", "alt_seviye": "Sanal Saygı", "varsayilan_gorev": "Sanal ortamda bile kimse için kırıcı veya kötü bir kelime yazma.", "varsayilan_tefekkur": "Klavye arkasında olmak ahlak kurallarını değiştirir mi?"},
    42: {"faz": "Faz 3: Pusula", "ust_seviye": "18. Dijital Mahremiyet", "alt_seviye": "Alternatif Üretme", "varsayilan_gorev": "Ekran yerine yapabileceğin 3 eğlenceli ev içi aktivite listesi yap.", "varsayilan_tefekkur": "İnsanın kendi eğlencesini kurabilmesi bir özgürlük müdür?"},

    # ==========================================
    # FAZ 4: AYNALAR (43 - 56. Adımlar)
    # ==========================================
    43: {"faz": "Faz 4: Aynalar", "ust_seviye": "19. Adabı Muaşeret", "alt_seviye": "Göz Teması", "varsayilan_gorev": "Biri seninle konuşurken işini bırakıp doğrudan gözlerine bak.", "varsayilan_tefekkur": "Karşındakine değer verdiğini hissettirmek bağı nasıl etkiledi?"},
    44: {"faz": "Faz 4: Aynalar", "ust_seviye": "19. Adabı Muaşeret", "alt_seviye": "Güzel Hitap", "varsayilan_gorev": "İnsanlara isimleriyle veya onurlandırıcı sıfatlarla hitap et.", "varsayilan_tefekkur": "İsminin güzel söylenmesi insanın kalbini yumuşatır mı?"},
    45: {"faz": "Faz 4: Aynalar", "ust_seviye": "20. Duygu Yönetimi", "alt_seviye": "Öfke Kontrolü", "varsayilan_gorev": "Kızdığın bir anda tepki vermeden önce derin bir nefes al.", "varsayilan_tefekkur": "Öfkeyi yutmak, ateşi suya çevirmek gibi midir?"},
    46: {"faz": "Faz 4: Aynalar", "ust_seviye": "20. Duygu Yönetimi", "alt_seviye": "Duygu İfadesi", "varsayilan_gorev": "Seni üzen bir şeyi bağırarak değil, sebebini açıklayarak söyle.", "varsayilan_tefekkur": "Duygunu doğru ifade etmek, karşı tarafın seni anlamasını kolaylaştırdı mı?"},
    47: {"faz": "Faz 4: Aynalar", "ust_seviye": "21. Empati", "alt_seviye": "Diğerinin Gözünden", "varsayilan_gorev": "Bugün üzgün görünen birinin yerine kendini koy ve ne hissettiğini düşün.", "varsayilan_tefekkur": "Onun ayakkabılarıyla yürümek fikrini değiştirdi mi?"},
    48: {"faz": "Faz 4: Aynalar", "ust_seviye": "21. Empati", "alt_seviye": "Yardım Teklifi", "varsayilan_gorev": "Zorlanan veya yorulan birine 'Yardıma ihtiyacın var mı?' diye sor.", "varsayilan_tefekkur": "El uzatmak sadece karşındakini değil, seni de iyileştirir mi?"},
    49: {"faz": "Faz 4: Aynalar", "ust_seviye": "22. Özsaygı", "alt_seviye": "Beden Dili", "varsayilan_gorev": "Omuzlarını dikleştir ve kendine güvenerek yürü.", "varsayilan_tefekkur": "Bedeninin duruşu, zihnindeki gücü etkiliyor mu?"},
    50: {"faz": "Faz 4: Aynalar", "ust_seviye": "22. Özsaygı", "alt_seviye": "Sınır Çizme", "varsayilan_gorev": "Hoşlanmadığın bir şaka yapıldığında net bir şekilde 'Hayır' de.", "varsayilan_tefekkur": "Kendi sınırlarını korumak sana saygı duyulmasını sağlar mı?"},
    51: {"faz": "Faz 4: Aynalar", "ust_seviye": "22. Özsaygı", "alt_seviye": "Olumlu İç Konuşma", "varsayilan_gorev": "Hata yaptığında kendine kızmak yerine 'Bir dahakine daha iyi yapacağım' de.", "varsayilan_tefekkur": "Kendinle arkadaş olmak başkalarıyla arkadaş olmaktan daha mı önemli?"},
    52: {"faz": "Faz 4: Aynalar", "ust_seviye": "23. Eleştiri Kültürü", "alt_seviye": "Özür Dileme", "varsayilan_gorev": "Kırdığın veya haksızlık yaptığın biri varsa içtenlikle özür dile.", "varsayilan_tefekkur": "Özür dilemek küçülmek midir, yoksa büyümek mi?"},
    53: {"faz": "Faz 4: Aynalar", "ust_seviye": "23. Eleştiri Kültürü", "alt_seviye": "Eleştiri Kabulü", "varsayilan_gorev": "Biri hatanı söylediğinde savunmaya geçmeden sadece dinle.", "varsayilan_tefekkur": "Dışarıdan gelen uyarılar göremediğin kör noktaları aydınlatır mı?"},
    54: {"faz": "Faz 4: Aynalar", "ust_seviye": "24. İfade ve Hitabet", "alt_seviye": "Net Anlatım", "varsayilan_gorev": "Düşünceni acele etmeden, kelimeleri yutmadan tane tane anlat.", "varsayilan_tefekkur": "Açık ve net konuşmak iletişimi nasıl kolaylaştırır?"},
    55: {"faz": "Faz 4: Aynalar", "ust_seviye": "24. İfade ve Hitabet", "alt_seviye": "İtiraz Ahlakı", "varsayilan_gorev": "Bir fikre katılmıyorsan, kaba olmadan saygıyla itiraz et.", "varsayilan_tefekkur": "Kırmadan 'Hayır' demek bir sanat mıdır?"},
    56: {"faz": "Faz 4: Aynalar", "ust_seviye": "24. İfade ve Hitabet", "alt_seviye": "Kendini Affetme", "varsayilan_gorev": "Yaptığın bir hatadan ders çıkar ve kendini gereksiz yere suçlamayı bırak.", "varsayilan_tefekkur": "Tövbe edip yeniden başlamak insanın en büyük gücü müdür?"},

    # ==========================================
    # FAZ 5: ÇARKLAR (57 - 70. Adımlar)
    # ==========================================
    57: {"faz": "Faz 5: Çarklar", "ust_seviye": "25. Bütçe Disiplini", "alt_seviye": "3 Gün Kuralı", "varsayilan_gorev": "Gördüğün bir oyuncağı/abur cuburu hemen alma, 3 gün bekle.", "varsayilan_tefekkur": "Beklemek o eşyaya olan arzunu azalttı mı?"},
    58: {"faz": "Faz 5: Çarklar", "ust_seviye": "25. Bütçe Disiplini", "alt_seviye": "Harçlık Biriktirme", "varsayilan_gorev": "Harçlığının küçük bir kısmını harcamadan kumbarana ayır.", "varsayilan_tefekkur": "Gelecek için biriktirmek sana güven veriyor mu?"},
    59: {"faz": "Faz 5: Çarklar", "ust_seviye": "26. İsraf Bilinci", "alt_seviye": "Elektrik Tasarrufu", "varsayilan_gorev": "Odadan çıkarken ışıkları kapatmayı unutma.", "varsayilan_tefekkur": "İhtiyacından fazlasını kullanmamak doğaya saygı mıdır?"},
    60: {"faz": "Faz 5: Çarklar", "ust_seviye": "26. İsraf Bilinci", "alt_seviye": "Su Tasarrufu", "varsayilan_gorev": "Diş fırçalarken veya sabunlanırken suyu boşuna akıtma.", "varsayilan_tefekkur": "Bir damla suyun kıymetini bilmek seni nasıl bir insan yapar?"},
    61: {"faz": "Faz 5: Çarklar", "ust_seviye": "27. Üretim Sevinci", "alt_seviye": "Kendi Oyuncağını Yap", "varsayilan_gorev": "Atık malzemelerden (karton, şişe) yeni bir şey üret.", "varsayilan_tefekkur": "Tüketici olmak yerine üretici olmak sana nasıl bir haz verdi?"},
    62: {"faz": "Faz 5: Çarklar", "ust_seviye": "27. Üretim Sevinci", "alt_seviye": "Tamir Kültürü", "varsayilan_gorev": "Bozulan bir eşyanı hemen atmak yerine tamir etmeye çalış.", "varsayilan_tefekkur": "Eşyaları onarmak, ilişkileri onarmaya da benzer mi?"},
    63: {"faz": "Faz 5: Çarklar", "ust_seviye": "28. Araştırma ve Gelişim", "alt_seviye": "Yeni Bir Şey Öğren", "varsayilan_gorev": "Bugün sözlükten veya bir kitaptan yepyeni bir kelime öğren.", "varsayilan_tefekkur": "Yeni bir bilgi zihninde yeni bir pencere açtı mı?"},
    64: {"faz": "Faz 5: Çarklar", "ust_seviye": "28. Araştırma ve Gelişim", "alt_seviye": "Soru Sorma", "varsayilan_gorev": "Merak ettiğin, mantığını anlamadığın bir konuyu büyüklere sor.", "varsayilan_tefekkur": "Merak etmek öğrenmenin anahtarı mıdır?"},
    65: {"faz": "Faz 5: Çarklar", "ust_seviye": "29. Hedef Koyma", "alt_seviye": "Küçük Adımlar", "varsayilan_gorev": "Gözünde büyüyen bir ödevi veya işi 3 küçük parçaya bölerek başla.", "varsayilan_tefekkur": "Dağı tırmanmak için sadece ilk adımı atmak yeterli midir?"},
    66: {"faz": "Faz 5: Çarklar", "ust_seviye": "29. Hedef Koyma", "alt_seviye": "Vazgeçmeme", "varsayilan_gorev": "Zorlandığın bir oyunu veya soruyu hemen bırakma, bir daha dene.", "varsayilan_tefekkur": "Başarı, düşmemek değil; düştükten sonra kalkmak mıdır?"},
    67: {"faz": "Faz 5: Çarklar", "ust_seviye": "29. Hedef Koyma", "alt_seviye": "Sonuçlandırma", "varsayilan_gorev": "Yarım bıraktığın bir işi, resmi veya kitabı bugün bitir.", "varsayilan_tefekkur": "Başladığın işi bitirmek iradeni nasıl çelikleştirir?"},
    68: {"faz": "Faz 5: Çarklar", "ust_seviye": "30. Emek ve Çaba", "alt_seviye": "Hazıra Konmama", "varsayilan_gorev": "İstediğin bir şeyi başkasından beklemek yerine kendin yapmaya çabala.", "varsayilan_tefekkur": "Emek vererek elde edilen şey neden daha kıymetlidir?"},
    69: {"faz": "Faz 5: Çarklar", "ust_seviye": "30. Emek ve Çaba", "alt_seviye": "Çalışma Saygısı", "varsayilan_gorev": "Dışarıda çalışan birini gördüğünde (temizlikçi, işçi) 'Kolay gelsin' de.", "varsayilan_tefekkur": "Emeğe saygı duymak toplumu nasıl güzelleştirir?"},
    70: {"faz": "Faz 5: Çarklar", "ust_seviye": "30. Emek ve Çaba", "alt_seviye": "Erken Kalkma", "varsayilan_gorev": "Tatil gününde bile öğlene kadar uyumak yerine erken kalkıp güne başla.", "varsayilan_tefekkur": "Sabahın sessizliği ve tazeliği ruhuna nasıl bir güç verdi?"},

    # ==========================================
    # FAZ 6: KÖPRÜLER (71 - 84. Adımlar)
    # ==========================================
    71: {"faz": "Faz 6: Köprüler", "ust_seviye": "31. Mahalle Kültürü", "alt_seviye": "Selamlaşma", "varsayilan_gorev": "Bugün apartmanda karşılaştığın bir komşuna tebessümle 'Merhaba' de.", "varsayilan_tefekkur": "Küçük bir selamın bir insanın gününü güzelleştirmesi sence mümkün mü?"},
    72: {"faz": "Faz 6: Köprüler", "ust_seviye": "31. Mahalle Kültürü", "alt_seviye": "Gürültü Yapmama", "varsayilan_gorev": "Gece geç saatlerde alt/üst komşuyu rahatsız etmemek için sessiz ol.", "varsayilan_tefekkur": "Başkasının huzurunu korumak bir ahlak göstergesi midir?"},
    73: {"faz": "Faz 6: Köprüler", "ust_seviye": "32. Doğa Sevgisi", "alt_seviye": "Çevre Temizliği", "varsayilan_gorev": "Dışarıda gördüğün bir çöpü (sana ait olmasa bile) alıp çöpe at.", "varsayilan_tefekkur": "Dünya senin de evin; onu temiz tutmak sana ne hissettiriyor?"},
    74: {"faz": "Faz 6: Köprüler", "ust_seviye": "32. Doğa Sevgisi", "alt_seviye": "Bitki Dikimi", "varsayilan_gorev": "Bir saksıya tohum ek veya var olan çiçeğin toprağını havalandır.", "varsayilan_tefekkur": "Toprakla bağ kurmak insanı köklerine yaklaştırır mı?"},
    75: {"faz": "Faz 6: Köprüler", "ust_seviye": "33. Canlılara Merhamet", "alt_seviye": "Hayvan Besleme", "varsayilan_gorev": "Kapının önüne sokak hayvanları için bir kap su veya mama koy.", "varsayilan_tefekkur": "Sana teşekkür edemeyecek birine iyilik yapmak ne demek?"},
    76: {"faz": "Faz 6: Köprüler", "ust_seviye": "33. Canlılara Merhamet", "alt_seviye": "İncitmeme", "varsayilan_gorev": "Yürürken yerdeki karıncalara veya küçük canlılara basmamaya dikkat et.", "varsayilan_tefekkur": "En zayıf olana merhamet etmek insanın kalitesini belirler mi?"},
    77: {"faz": "Faz 6: Köprüler", "ust_seviye": "34. Toplumsal Sorumluluk", "alt_seviye": "Sıra Bekleme", "varsayilan_gorev": "Market kasasında veya parkta kimsenin hakkını yemeden sıranı bekle.", "varsayilan_tefekkur": "Kurallara uymak adaletin en küçük parçası mıdır?"},
    78: {"faz": "Faz 6: Köprüler", "ust_seviye": "34. Toplumsal Sorumluluk", "alt_seviye": "Trafik Kuralları", "varsayilan_gorev": "Yoldan geçerken yaya geçidini kullan ve ışıklara dikkat et.", "varsayilan_tefekkur": "Toplum hayatını düzenleyen kurallar hepimizi korur mu?"},
    79: {"faz": "Faz 6: Köprüler", "ust_seviye": "35. Yardımlaşma", "alt_seviye": "Yük Taşıma", "varsayilan_gorev": "Eline poşet taşıyan bir büyüğüne 'Yardım edebilir miyim?' diye sor.", "varsayilan_tefekkur": "Birinin yükünü hafifletmek kendi kalbini de hafifletir mi?"},
    80: {"faz": "Faz 6: Köprüler", "ust_seviye": "35. Yardımlaşma", "alt_seviye": "Paylaşma İradesi", "varsayilan_gorev": "Çok sevdiğin bir yiyeceği arkadaşınla veya kardeşinle bölüş.", "varsayilan_tefekkur": "Paylaşılan lokmanın bereketi artar mı?"},
    81: {"faz": "Faz 6: Köprüler", "ust_seviye": "35. Yardımlaşma", "alt_seviye": "Rehberlik", "varsayilan_gorev": "Bir eşyasını arayan veya yolunu kaybeden birine yardımcı ol.", "varsayilan_tefekkur": "Karanlıkta başkasına fener olmak kendi yolunu da aydınlatır mı?"},
    82: {"faz": "Faz 6: Köprüler", "ust_seviye": "36. Ortak Malı Koruma", "alt_seviye": "Park Eşyası", "varsayilan_gorev": "Parktaki salıncağı veya oyuncakları kırmadan, özenle kullan.", "varsayilan_tefekkur": "Senden sonrakileri düşünmek erdemli bir davranış mıdır?"},
    83: {"faz": "Faz 6: Köprüler", "ust_seviye": "36. Ortak Malı Koruma", "alt_seviye": "Okul Sırası", "varsayilan_gorev": "Sıranı çizmeme ve temiz tutma konusunda özen göster.", "varsayilan_tefekkur": "Devletin veya okulun malı aslında hepimizin malı mıdır?"},
    84: {"faz": "Faz 6: Köprüler", "ust_seviye": "36. Ortak Malı Koruma", "alt_seviye": "Karşılıksız İyilik", "varsayilan_gorev": "Bugün ailen için onların haberi olmadan gizli bir iyilik yap.", "varsayilan_tefekkur": "Karşılık beklemeden yapılan eylemin sırrı sence nedir?"},

    # ==========================================
    # FAZ 7: KANATLAR (85 - 99. Adımlar)
    # ==========================================
    85: {"faz": "Faz 7: Kanatlar", "ust_seviye": "37. Mentorluk Liyakati", "alt_seviye": "Küçüğe Rehberlik", "varsayilan_gorev": "Kardeşine veya senden küçük birine bildiğin bir oyunu/dersi sabırla öğret.", "varsayilan_tefekkur": "Bilgini paylaşmak ve birinin hayatına dokunmak ruhunu nasıl besledi?"},
    86: {"faz": "Faz 7: Kanatlar", "ust_seviye": "37. Mentorluk Liyakati", "alt_seviye": "Sabırla Anlatma", "varsayilan_gorev": "Arkadaşın bir konuyu anlamadığında sinirlenmeden tekrar izah et.", "varsayilan_tefekkur": "Öğretirken aslında kendin de yeniden öğrenir misin?"},
    87: {"faz": "Faz 7: Kanatlar", "ust_seviye": "37. Mentorluk Liyakati", "alt_seviye": "Örnek Olma", "varsayilan_gorev": "Küçüklerin yanında davranışlarına ve kelimelerine iki kat dikkat et.", "varsayilan_tefekkur": "Birine rol model olmak insana nasıl bir sorumluluk yükler?"},
    88: {"faz": "Faz 7: Kanatlar", "ust_seviye": "38. Manevi Derinlik", "alt_seviye": "Dua ve İyi Niyet", "varsayilan_gorev": "Bugün tanımadığın veya kızdığın biri için içinden sessizce iyilik dile.", "varsayilan_tefekkur": "Başkası için iyi şeyler dilemek kendi kalbindeki kiri temizler mi?"},
    89: {"faz": "Faz 7: Kanatlar", "ust_seviye": "38. Manevi Derinlik", "alt_seviye": "Şükür Defteri", "varsayilan_gorev": "Bugün sahip olduğun ve şükrettiğin 3 güzel şeyi bir kenara yaz.", "varsayilan_tefekkur": "Sahip olduklarına odaklanmak eksiklerini unutturdu mu?"},
    90: {"faz": "Faz 7: Kanatlar", "ust_seviye": "39. Erdemli Davranış", "alt_seviye": "Doğruluk", "varsayilan_gorev": "Sonucunda ceza alacak bile olsan yalan söyleme, doğruyu konuş.", "varsayilan_tefekkur": "Yalanın yükünü taşımaktansa, doğrunun bedelini ödemek daha mı hafiftir?"},
    91: {"faz": "Faz 7: Kanatlar", "ust_seviye": "39. Erdemli Davranış", "alt_seviye": "Sözünde Durma", "varsayilan_gorev": "Verdiğin bir sözü tam zamanında ve eksiksiz yerine getir.", "varsayilan_tefekkur": "Sözü senet olan bir insan olmak sana nasıl bir saygınlık kazandırır?"},
    92: {"faz": "Faz 7: Kanatlar", "ust_seviye": "39. Erdemli Davranış", "alt_seviye": "Adalet", "varsayilan_gorev": "Oyunda haksızlık yapıldığında, kendi aleyhine bile olsa adaleti savun.", "varsayilan_tefekkur": "Güçlünün değil, haklının yanında durmak cesaret ister mi?"},
    93: {"faz": "Faz 7: Kanatlar", "ust_seviye": "39. Erdemli Davranış", "alt_seviye": "Güvenilirlik", "varsayilan_gorev": "Sana emanet edilen bir sırrı veya eşyayı kendi canın gibi koru.", "varsayilan_tefekkur": "Emin (güvenilir) kişi olmak insanın ulaşabileceği en yüksek makam mıdır?"},
    94: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "Vefa", "varsayilan_gorev": "Sana emeği geçen birine (öğretmen/akraba) ulaşıp teşekkür et.", "varsayilan_tefekkur": "Vefa, iyiliği unutmamak ve kalbin hafızasını diri tutmak mıdır?"},
    95: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "Kusur Örtme", "varsayilan_gorev": "Bir arkadaşının veya kardeşinin hatasını yüzüne vurmak yerine gizle.", "varsayilan_tefekkur": "Kusur örtmek, kendi kusurlarının örtülmesine bir dua mıdır?"},
    96: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "İhlas", "varsayilan_gorev": "Bugün bir iyiliği kimse görmeden ve kimseden takdir beklemeden yap.", "varsayilan_tefekkur": "Sadece doğru olduğu için yapılan eylem en saf eylem midir?"},
    97: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "Tevazu", "varsayilan_gorev": "Bir işte çok başarılı olduğunda böbürlenmek yerine alçakgönüllü ol.", "varsayilan_tefekkur": "Meyve veren ağaç neden dallarını eğer?"},
    98: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "Şahsiyet Timsali", "varsayilan_gorev": "Zor bir olay karşısında tepki vermeden önce Kıvamını (sükunetini) koru.", "varsayilan_tefekkur": "Dışarıdaki fırtınalara rağmen içerdeki limanı sakin tutabildin mi?"},
    99: {"faz": "Faz 7: Kanatlar", "ust_seviye": "40. Kıvam (İhsan)", "alt_seviye": "Nefs Muhasebesi", "varsayilan_gorev": "Günü kapatırken tart, hataların için tövbe et, yarın için güzel niyet al.", "varsayilan_tefekkur": "99 adımlık bu yolculuğun sonunda kendi 'Kıvamına' ulaştığını hissediyor musun?"}
}